name: 'docker-build-action'
description: 'Simplified Docker image builds with Github Actions.'
inputs:
  tags:
    description: 'Enter the tag you would like to name your image with. (example: myorg/myapp:production)'
    required: true
  registry-username:
    description: 'Enter the username to authenticate with your registry.'
    required: true
  registry-token:
    description: 'Enter the token or password to authenticate with your registry. (an access token is highly recommended)'
    required: true
  registry:
    description: 'Choose which container image repository to upload to.'
    default: '' # Defaults to Docker Hub
    required: false
  context:
    description: 'The relative path to the Dockerfile.'
    default: '.'
    required: false
  platforms:
    description: 'Comma separated list of platforms.'
    default: 'linux/amd64'
    required: false
runs:
  using: 'composite'
  steps:
      - name: Login to Container Image Registry
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.registry-username }}
          password: ${{ inputs.registry-password }}
          registry: ${{ inputs.registry }}

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch-name.outputs.current_branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          platforms: ${{ inputs.platforms }}
          pull: true
          push: true
          tags: ${{ inputs.tags }}
branding:
  icon: 'server'
  color: 'blue'
