name: 'docker-build-action'
description: 'Simplified Docker image builds with Github Actions.'
inputs:
  tags:
    description: 'Enter the tag you would like to name your image with. (example: myorg/myapp:production)'
    required: true
  context:
    description: 'Path to the source Dockerfile'
    default: '.'
    required: false
  platforms:
    description: 'Comma separated list of platforms.'
    default: 'linux/amd64'
    required: false
runs:
  using: 'composite'
  steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          platforms: ${{ inputs.platforms }}
          pull: true
          push: true
          tags: ${{ inputs.tags }}
branding:
  icon: 'server'
  color: 'blue'
